version: "3"
services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - kousa
      - shawarma
    networks:
      - dogehouse
    restart: always

  shawarma:
    build: ./shawarma
    network_mode: "host"
    env_file:
      - shawarma.env
    restart: always

  kousa:
    build: ./kousa
    env_file:
      - kousa.env
    expose:
      - "4001"
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - dogehouse
    restart: always

  postgres:
    image: postgres:13
    env_file:
      - pg.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dogehouse
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    env_file:
      - rabbit.env
    networks:
      dogehouse:
        ipv4_address: 172.20.0.10
    restart: always

  adminer:
    image: adminer
    expose:
      - "8080"
    networks:
      - dogehouse
    restart: always

networks:
  dogehouse:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  postgres_data:
