name: kousa:deploy_staging
on:
  push:
    paths:
      - 'kousa/lib/**'
      - 'kousa/config/**'
    branches:
      - staging
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /root/dogehouse
            git pull origin staging
            docker compose build kousa
            docker compose up -d kousa
